[package]
name = "curve41417"
version = "0.0.1"
description = "A pure-Rust Curve41417 implementation"
license = "MIT/ASL2"
readme = "README.md"
authors = ["Sebastien Martini <seb@dbzteam.org>"]

[lib]
name = "curve41417"

# FIXME: temp
#[dependencies]
#rustc-serialize = "0.1.4"

[dependencies.rustc-serialize]
git = "https://github.com/rust-lang/rustc-serialize"

[dependencies.tars]
git = "https://github.com/seb-m/tars"
